version: '2'
services:
    poetryboy-admin:
        image: poetryboy:latest
        restart: always
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
          - ./src/:/usr/src/app
        ports:
          - 8001:8000
        environment:
          DEBUG: 1
    poetryboy-backend:
        image: poetryboy:latest
        restart: always
        command: gunicorn poetryboy.wsgi -w 4 -b 0.0.0.0:8000
        volumes:
          - ./src/:/usr/src/app
        environment:
          DEBUG: 1
    nginx:
        image: nginx:latest
        depends_on:
          - poetryboy-backend
        volumes:
          - ./ui/dist/:/ui
          - ./nginx.conf:/etc/nginx/conf.d/poetryboy.conf
        ports:
          - 8080:8080
